# Generated by Django 5.2.12 on 2026-03-28 10:17

import django.core.validators
import django.db.models.deletion
import reimbursement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('amount_limit', 'Amount Limit'), ('category_limit', 'Category Limit'), ('requires_receipt', 'Receipt Required Above Amount'), ('approval_tier', 'Extra Approval Tier')], max_length=20)),
                ('expense_category', models.CharField(blank=True, choices=[('project', 'Project Expense'), ('equipment', 'Equipment Purchase'), ('vendor', 'Vendor Expense'), ('marketing', 'Marketing Expense'), ('travel', 'Travel Expense'), ('training', 'Training & Development'), ('misc', 'Miscellaneous')], help_text='Blank = applies to all categories', max_length=15)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('claim_type', models.CharField(choices=[('expense', 'Expense Claim'), ('purchase', 'Purchase Claim')], max_length=10)),
                ('expense_category', models.CharField(choices=[('project', 'Project Expense'), ('equipment', 'Equipment Purchase'), ('vendor', 'Vendor Expense'), ('marketing', 'Marketing Expense'), ('travel', 'Travel Expense'), ('training', 'Training & Development'), ('misc', 'Miscellaneous')], max_length=15)),
                ('payment_type', models.CharField(choices=[('prepaid', 'Prepaid (Employee paid first)'), ('postpaid', 'Postpaid (Company pays vendor)')], default='prepaid', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='IDR', max_length=5)),
                ('expense_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('paid', 'Paid / Reimbursed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('policy_validated', models.BooleanField(default=False)),
                ('policy_notes', models.TextField(blank=True)),
                ('is_reusable', models.BooleanField(default=False, help_text='For purchase claims — is item reusable/asset?')),
                ('added_to_inventory', models.BooleanField(default=False)),
                ('po_number', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='budget_planning.budget')),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_planning.budgetcategory')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_to_review', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=reimbursement.models.claim_attachment_path)),
                ('file_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('quote', 'Quotation'), ('contract', 'Contract'), ('other', 'Other')], default='receipt', max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reimbursement.expenseclaim')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('policy_validated', 'Policy Validated'), ('policy_failed', 'Policy Check Failed'), ('paid', 'Payment Processed'), ('cancelled', 'Cancelled'), ('revised', 'Claim Revised')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='reimbursement.expenseclaim')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('wallet', 'Digital Wallet')], max_length=15)),
                ('payment_ref', models.CharField(blank=True, help_text='Bank ref / transaction ID', max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursement', to='reimbursement.expenseclaim')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements_processed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
